accounts/urls.py
# import models, views, and functions here
from django.urls import path
from accounts.views import (
    LoginLoginView,
    LogoutLogoutView,
    signup,
)

# url path patterns here

urlpatterns = [
    path("login/", LoginLoginView.as_view(), name="login"),
    path("logout/", LogoutLogoutView.as_view(), name="logout"),
    path("signup/", signup, name="signup"),
]

expenses/urls.py
from django.contrib import admin
from django.urls import path, include, reverse_lazy
from django.views.generic import RedirectView


urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("receipts/", include("receipts.urls")),
    path("", RedirectView.as_view(url=reverse_lazy("home"))),
]

receipts/urls.py
from django.urls import path

from receipts.views import (
    ReceiptListView,
    ReceiptCreateView,
    ExpenseCategoryCreateView,
    AccountsCreateView,
    AccountsListView,
    ExpenseCategoryListView,
)

urlpatterns = [
    path("", ReceiptListView.as_view(), name="home"),
    path("create/", ReceiptCreateView.as_view(), name="receipt_create"),
    path(
        "accounts/create/",
        AccountsCreateView.as_view(),
        name="accounts_create",
    ),
    path("accounts/", AccountsListView.as_view(), name="accounts_list"),
    path(
        "categories/create/",
        ExpenseCategoryCreateView.as_view(),
        name="expense_category_create",
    ),
    path(
        "categories/",
        ExpenseCategoryListView.as_view(),
        name="expense_category_list",
    ),
]

accounts/models.py
from django.db import models


# Create your models here.

receipts/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class ExpenseCategory(models.Model):
    name = models.CharField(max_length=50)
    owner = models.ForeignKey(
        User, related_name="categories", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Account(models.Model):
    name = models.CharField(max_length=100)
    number = models.CharField(max_length=20)
    owner = models.ForeignKey(
        User, related_name="accounts", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name


class Receipt(models.Model):
    vendor = models.CharField(max_length=200)
    total = models.DecimalField(decimal_places=3, max_digits=10)
    tax = models.DecimalField(decimal_places=3, max_digits=10)
    date = models.DateField(null=True)
    purchaser = models.ForeignKey(
        User, related_name="receipts", on_delete=models.CASCADE
    )
    category = models.ForeignKey(
        ExpenseCategory, related_name="receipts", on_delete=models.CASCADE
    )
    account = models.ForeignKey(
        Account, related_name="receipts", on_delete=models.CASCADE, null=True
    )

accounts/views.py
from django.shortcuts import redirect, render
from django.contrib.auth import login
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# Create your views here.


class LoginLoginView(LoginView):
    template_name = "registration/login.html"


class LogoutLogoutView(LogoutView):
    template_name = "registration/logged_out.html"


def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            username = request.POST.get("username")
            password = request.POST.get("password1")
            user = User.objects.create_user(
                username=username, password=password
            )
            user.save()
            login(request, user)
            return redirect("home")
    else:
        form = UserCreationForm()
    context = {
        "form": form,
    }
    return render(request, "registration/signup.html", context)

receipts/views.py
from msilib.schema import ListView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from receipts.models import ExpenseCategory, Account, Receipt

# Create your views here.


class ReceiptListView(LoginRequiredMixin, ListView):
    model = Receipt
    template_name = "receipts/list.html"

    def get_queryset(self):
        return Receipt.objects.filter(purchaser=self.request.user)


class ReceiptCreateView(CreateView):
    model = Receipt
    template_name = "receipts/create.html"
    fields = [
        "vendor",
        "total",
        "tax",
        "date",
        "purchaser",
        "category",
        "account",
    ]

    def form_valid(self, form):
        receipts = form.save(commit=False)
        receipts.purchaser = self.request.user
        receipts.save()
        return redirect("home")

    def get_success_url(self):
        return reverse_lazy("home")


class ExpenseCategoryListView(ListView):
    model = ExpenseCategory
    template_name = "receipts/categories/list.html"

    def get_query_set(self):
        return ExpenseCategory.objects.filter(owner=self.request.user)


class ExpenseCategoryCreateView(CreateView):
    model = ExpenseCategory
    template_name = "receipts/categories/create.html"
    fields = [
        "name",
        "owner",
    ]

    def form_valid(self, form):
        categories = form.save(commit=False)
        categories.owner = self.request.user
        categories.save()
        return redirect("expense_category_list")


class AccountsListView(ListView):
    model = Account
    template_name = "receipts/accounts/list.html"

    def get_queryset(self):
        return Account.objects.filter(owner=self.request.user)


class AccountsCreateView(CreateView):
    model = Account
    template_name = "receipts/accounts/create.html"
    fields = ["name", "number", "owner"]

    def form_valid(self, form):
        accounts = form.save(commit=False)
        accounts.owner = self.request.user
        accounts.save()
        return redirect("accounts_list")


# def get_success_url(self):
#         return reverse_lazy("expense_category_list")

receipts/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Title</title>
  {% comment %} <link rel="stylesheet" href="{% static 'css/app.css' %}"> {% endcomment %}
</head>
<body>
    <header>
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">
                <button>Logout</button>
            </a>
            <p></p>
            <a href="{% url 'home' %}">
                <button>Home</button>
            </a>
            <p></p>
            <a href="{% url 'expense_category_create' %}"> Create Expense Category </a>
            <a href="{% url 'accounts_create' %}"> Create Account </a>
            <a href="{% url 'receipt_create' %}"> Create Receipt </a>
            <p></p>
            <a href="{% url 'expense_category_list' %}">Expense Category List</a>
            <a href="{% url 'accounts_list' %}">Account List</a>
        {% else %}
            <a href="{% url 'signup' %}">Sign Up</a>
            <a href="{% url 'login' %}">Login</a>
        {% endif %}
    </header>
    {% block content %}
    {% endblock content %}
</body>
</html>

receipts/templates/receipts/accounts/create.html
{% extends 'base.html' %}
{% block content %}
<main>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Submit Account</button>
    </form>
</main>
{% endblock content %}

receipts/templates/receipts/accounts/list.html
{% extends 'base.html' %}
{% block content %}
<main>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number</th>
                <th>Number of Receipts</th>
            </tr>
        </thead>
        <tbody>
            {% for account in account_list %}
            <tr>
                <td>{{ account.name }}</td>
                <td>{{ account.number }}</td>
                <td>{{ account.receipts.all|length }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{% endblock content %}

receipts/templates/receipts/categories/create.html
{% extends 'base.html' %}
{% block content %}
<main>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Submit Category</button>
    </form>
</main>
{% endblock content %}

receipts/templates/receipts/categories/list.html
{% extends 'base.html' %}
{% block content %}
<main>
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Number of receipts</th>
            </tr>
        </thead>
        <tbody>
            {% for category in expensecategory_list %}
            <tr>
                <td>{{ category.name }}</td>
                <td>{{ category.receipts.all|length }}</td>
            </tr>
            {% endfor %}
        </tbody>
</main>
{% endblock content %}

receipts/templates/receipts/create.html
{% extends 'base.html' %}
{% block content %}
<main>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button>Submit Receipt</button>
    </form>
</main>
{% endblock content %}

receipts/templates/receipts/list.html
{% extends 'base.html' %}
{% block content %}
<main>
    <table>
        <thead>
            <tr>
                <th>Vendor</th>
                <th>Total</th>
                <th>Tax</th>
                <th>Date</th>
                <th>Category</th>
                <th>Account</th>
            </tr>
        </thead>
        <tbody>
            {% for receipt in receipt_list %}
            <tr>
                <td>{{ receipt.vendor }}</td>
                <td>{{ receipt.total }}</td>
                <td>{{ receipt.tax }}</td>
                <td>{{ receipt.date }}</td>
                <td>{{ receipt.category }}</td>
                <td>{{ receipt.account }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</main>
{% endblock content %}